### ISSUE TITLE
Is this still maintained?

### ISSUE THREAD

**Issue by DomtronVox** [LiveAsynchronousVisualizedArchitecture/simdb#2]
Hi I was wondering if you plan to continue maintaining this repo. That last update to the core file was 5 months ago but I noticed the same file over on your https://github.com/LiveAsynchronousVisualizedArchitecture/lava which was updated around 19 days ago. Should I use this repo or just extract that file from the LAVA repo for my uses?

Mostly asking because I wanted to make sure whether the changes to the DB library in the LAVA repo was specific to that project or if the changes were generally useful.

Thanks for making this project!

**Comment by LiveAsynchronousVisualizedArchitecture** [comment]
Hey, I'm glad you are interested (and paying close attention).  The lava file you saw was more recent and fixed some subtle concurrency bugs.  The simdb file should be updated to reflect that now.  I actually didn't realize anyone was paying attention and didn't put the changes in right away.  If you are using this for something, let me know and I can work with you to make sure it goes well.   For the most part, I have been using it in the LAVA node graph, and after a few fixes a couple of months ago, it has continued to work without problems. 

The next big step is probably getting some sort of dynamic resizing to work.  Right now the db file size is dictated by the parameters when it is created (first program to make the file wins).

**Comment by NickNaso** [comment]
Hi everybody,
I'm experimenting the library and after that my purpose is to create a node.js native addon-on that will allow use the SimDB API directly from JavaScript. 
Here you can find the initial project I hope to end very soon https://github.com/NickNaso/node-simdb

**Comment by LiveAsynchronousVisualizedArchitecture** [comment]
@NickNaso That's exciting.  I could see that being used for interprocess communication from node.js processes to native processes, as well as a way to cache large chunks of data.   Let me know if you have any questions, run into any snags, or want input on design.

**Comment by NickNaso** [comment]
Hi @LiveAsynchronousVisualizedArchitecture,
thank for your availability. I will keep update you when we will make progress on the project.

**Comment by LiveAsynchronousVisualizedArchitecture** [comment]
@NickNaso Sounds good.

@DomtronVox I will close this issue in a day unless there is a reason to keep it open.  We can still have discussions under new issues and in other areas obviously.
